package tienda.Usuarios;

public enum TipoPermisos {
	GESTION_STOCK,
	GESTION_CATEGORIAS,
	GESTION_PACKS,
	MODIFICAR_PRODUCTO,
	GESTION_PEDIDOS,
	VALORACION_PRODUCTOS,
	CONFIRMACION_INTERCAMBIO,
	ENTREGA_PEDIDOS
}
